# Generated by Django 5.0.1 on 2024-02-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_information_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=1000)),
                ('Username', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Customer_Name', models.CharField(max_length=250)),
                ('Vendor', models.CharField(max_length=250)),
                ('Account_number', models.CharField(max_length=250)),
                ('User_email_id', models.CharField(max_length=250)),
                ('Automated', models.CharField(max_length=250)),
                ('On_Email', models.CharField(max_length=250)),
            ],
        ),
    ]
