# Generated by Django 5.0.1 on 2024-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_portal_information_data_delete_portal_info_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=255)),
                ('bill_date', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
