# Generated by Django 5.0.1 on 2024-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_user_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_filename', models.CharField(max_length=255)),
                ('contract_pdf_path', models.FileField(upload_to='contracts/')),
            ],
        ),
    ]
